export const ASCENDING = 'asc'
export const DESCENDING = 'desc'
export const EXPERIENCE = 'year_of_experience'
export const POSITION_APPLIED = 'position_applied'
export const APPLICATION_DATE = 'application_date'
export const APPLICANT_NAME = 'name'
export const APPLICATION_STATUS = 'status'
